import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/client.ts",
    "src/compat/web.ts",
    "src/connection-pool.ts",
    "src/dns-cache.ts",
    "src/protocol-cache.ts",
    "src/http1/chunked.ts",
    "src/http1/client.ts",
    "src/http1/parser.ts",
    "src/http2/client.ts",
    "src/http2/connection.ts",
    "src/http2/constants.ts",
    "src/http2/flow-control.ts",
    "src/http2/framer.ts",
    "src/http2/hpack.ts",
    "src/http2/parser.ts",
    "src/http2/stream.ts",
    "src/lite/index.ts",
    "src/socket/adapter.ts",
    "src/socket/cloudflare-ranges.ts",
    "src/socket/nat64-health.ts",
    "src/socket/nat64.ts",
    "src/socket/tls.ts",
    "src/socket/wasm-tls-adapter.ts",
    "src/socket/wasm-tls-bridge.ts",
    "src/utils/headers.ts",
    "src/utils/url.ts",
    "src/web/bytes.ts",
    "src/web/client.ts",
    "src/web/full-strategy.ts",
    "src/web/http1/chunked.ts",
    "src/web/http1/client.ts",
    "src/web/http1/parser.ts",
    "src/web/index.ts",
    "src/web/raw-socket.ts",
    "src/web/request-utils.ts",
    "src/web/wasm-tls.ts",
    "src/web/wasm-transport.ts",
  ],
  format: ["esm"],
  dts: true,
  clean: true,
  splitting: false,
  bundle: false,
  outDir: "dist",
  external: ["cloudflare:sockets", "hpack.js"],
});
